accomplishment/urls.py
from django.urls import path, re_path
from . import views
from . import requests

# Ideally, its name is identical with the folder's
app_name = "accomplishment"

urlpatterns = [
     # path(<URL>, <view>, <name>)
     re_path(r"^(?:show=(?P<popup>[a-zA-Z_]+)/)?$", views.page_overview, name="overview"),

     # AJAX Urls
     re_path(r"^get/(?:amount=(?P<amount>[0-9]+)/)?(?:start=(?P<start>[0-9]+)/)?(?:selector='(?P<selector>[a-zA-Z]+)'/)?(?:key='(?P<key>[0-9a-zA-Z ]+)')?$",
          requests.get_entries, name="get"),
     path("get/recent/amount=<int:amount>",
          requests.get_recent, name="get_recent"),
     path("get/today/amount=<int:amount>",
          requests.get_obtained_today, name="obtained_today"),
     path("get/name=<str:name>",
          requests.get_by_name, name="get_by_name"),
     path("get/names",
          requests.get_names, name="get_names"),

     path("entry/get/id=<uuid:ID>",
          requests.get_accomp_by_id, name="get_by_id"),
     path("entry/edit/id=<uuid:ID>",
          requests.edit_accomp, name="edit_accomp"),
     path("entry/repeat",
          requests.repeat_accomplishment, name="repeat_accomp"),
     path("template/get", requests.get_template, name="get_template"),
     path("template/save", requests.save_template, name="save_template"),

     # Operations (Creating/Deleting)
     path("submit",
          requests.submit_accomplishment, name="submit_new"),
     path("delete/id=<uuid:ID>",
          requests.delete_accomplishment, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),  # Main App ('core')
    path("accomplishments/",  # Accomplishment
         include("accomplishment.urls", namespace='accomplishment')),
    path("admin/", admin.site.urls),
    path("finance/",          # Finance
         include("finance.urls", namespace='finance')),
    path("calendar/",          # Finance
         include("ft_calendar.urls", namespace='calendar')),
]

core/urls.py
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from core.session import switch_language, switch_family
from . import views, requests, user_auth

# Ideally, its name is identical with the folder's
app_name = "core"

core_urls = [
    # path(<URL>, <view>, <name>)
    path("", views.home, name="home"),
    path("login/", views.user_login_page, name="user_login"),
    path("register/", views.user_register, name="user_register"),
    path("register/final_step/", views.user_final_step, name="user_final_step"),
    path("profile/", views.user_profile_page, name="user_profile"),
    path("settings/", views.user_settings_page, name="user_settings"),
    path("family/", views.manage_family_page, name="manage_family"),

    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path("password_reset_sent/<str:reset_id>/", views.password_reset_sent, name="password_reset_sent"),
    path("reset_password/<str:reset_id>/", views.reset_password, name="reset_password"),

    # Authentication and Session (AJAX)
    path("auth/login", user_auth.process_login, name="request_login"),
    path("auth/logout", user_auth.process_logout, name="request_logout"),
    path("session/switch_language", switch_language,
         name="session_change_language"),
    path("session/switch_family?id=<int:id>", switch_family,
         name="session_switch_family"),

    # Family (AJAX)
    path("family/create", requests.create_family, name="create_family"),
    path("family/join", requests.join_family, name="join_family"),
    path("family/check_invite", requests.check_invite, name="check_invite"),
    path("family/create_invite", requests.create_invite, name="create_invite"),
    path("family/remove_member", requests.remove_from_family, name="remove_member"),
    path("family/toggle_manager_role", requests.toggle_manager_role, name="toggle_manager_role"),
    path("family/get_user", requests.get_user, name="get_user"),

    # Messenger (AJAX)
    path("message/delete/id=<uuid:id>", requests.delete_message,
         name="delete_message"),
    path("get_messages/", requests.get_messages, name="get_messages"),
]

urlpatterns = [
    # Import core_urls twice to include variants
    # with and without a provided language code
    re_path(r"^(?P<lang_code>[a-z]{2,3})/", include(core_urls)),
    path("", include(core_urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ft_calendar/urls.py
from django.urls import path, re_path
from . import views

# Ideally, its name is identical with the folder's
app_name = "calendar"

urlpatterns = [
     # path(<URL>, <view>, <name>)
     re_path(r"^(?:start=(?P<start>[0-9]+)/)?$", views.page_calendar, name="calendar"),
     path("get", views.get, name="get"),
     path("create/", views.create_or_edit_calendar_entry, name="create_event"),
     path("edit/<int:event_id>/", views.create_or_edit_calendar_entry, name="calendar_edit"),
     path("delete/<int:event_id>/", views.delete_calendar_entry, name="calendar_delete"),
]

core/models/business_entity.py
from django.db import models

class BusinessEntity(models.Model):
    id = models.BigIntegerField(
        primary_key=True,
        unique=True
        )
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)

core/forms/user_final_step.py
from django import forms


class UserFinalizeForm(forms.Form):
    family_name = forms.CharField(
        label="", max_length=100, required=False)
    invite_code = forms.CharField(
        label="", max_length=50, required=False)

    family_name.widget.attrs.update({"style": "width: 20em;"})
    invite_code.widget.attrs.update({"style": "width: 20em;"})

core/forms/user_register.py
from django import forms


class UserRegisterForm(forms.Form):
    username = forms.CharField(
        label="User Name", max_length=24, required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(
        label="Password", required=True,
        min_length=8,
        widget=forms.PasswordInput())
    first_name = forms.CharField(
        label="First Name", max_length=20, required=False)
    last_name = forms.CharField(
        label="Last Name", max_length=20, required=False)
    invite_code = forms.CharField(
        label="", max_length=50, required=False)

    invite_code.widget.attrs.update({"style": "width: 20em;"})

core/forms/user_settings.py
from django import forms
from ..constants import COLORS, LANGUAGES, TIMEZONES, YEARS


class UserSettingsForm(forms.Form):
    first_name = forms.CharField(
        label="First Name", max_length=20, required=False)
    last_name = forms.CharField(
        label="Last Name", max_length=20, required=False)
    birthday = forms.DateField(
        required=False,
        widget=forms.SelectDateWidget(years=YEARS),
    )
    language = forms.ChoiceField(
        label="Language", choices=LANGUAGES, required=True)
    cursor = forms.BooleanField(
        label="Use Custom Cursor", required=False)
    color = forms.ChoiceField(
        label="Color", required=True, choices=COLORS)
    user_icon = forms.FileField(required=False)
    background_image = forms.FileField(required=False)
    remove_icon = forms.BooleanField(
        label="Remove Icon", required=False)
    remove_background = forms.BooleanField(
        label="Remove Background", required=False)

    #  Add Bootstrap classes to the fields
    cursor.widget.attrs.update({"class": "form-check-input", "style": "width: 2.5em; height: 1.5em;"})
    language.widget.attrs.update({"class": "form-select"})

core/views.py
import re
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import AnonymousUser
from django.contrib.auth.forms import AuthenticationForm
from django.core.mail import EmailMessage
from django.contrib import messages
from django.conf import settings
from django.db import transaction
from django.http import HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.shortcuts import render, redirect

from core.session import update_user_session
from .constants import COLORS
from .models import CustomUser, Family, FamilyUser, FamilyInvite, PasswordReset
from .forms import UserSettingsForm, UserRegisterForm, UserFinalizeForm
from .requests import join_family
from .session import update_session, create_alert

from accomplishment.models import FamilyUserAccomplishment
from messenger.models import FamilyChat, Message
from ft_calendar.models import CalendarEntry


# TODO: Switch to the new 'update_user_session' everywhere, then remove this.
def render_if_logged_in(request, target: HttpResponse):
    """Check if the User is logged in. Then, either proceed to the target page,
    or redirect them to the Login/Final Step page."""

    if not request.user.is_authenticated:
        create_alert(request=request, ID="login-required", type="warning",
                     text="For this action, you need to login first.")
        return redirect("core:user_login")

    try:
        FamilyUser.objects.filter(
            custom_user_id=request.user)[request.session["current_family"]]
        return target
    except (FamilyUser.DoesNotExist, IndexError):
        return redirect("core:user_final_step")


@update_user_session(require_login=False)
def home(request):
    """The Home page."""
    return render(request, "home/home.html", {})


PASSWORD_PATTERN = r"^(?=.*[A-Z])(?=.*[^A-Za-z0-9]).{8,}$"


@transaction.atomic
@update_user_session(require_login=False)
def user_register(request):

    # Redirect the user to the Overview if they're already logged in
    if request.user.is_authenticated:
        return redirect("core:user_profile")

    form: UserRegisterForm = UserRegisterForm()

    if request.method != "POST":
        return render(
            request, "core/user_register.html",
            {'form': form})
    else:
        form = UserRegisterForm(data=request.POST)

        # get posted fields:
        if form.is_valid():
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            first_name = form.cleaned_data.get("first_name", "")
            last_name = form.cleaned_data.get("last_name", "")

            # field validation:
            user_data_has_error = False
            if CustomUser.objects.filter(username=username).exists():
                user_data_has_error = True
                create_alert(request=request, ID="user-exists", type="error",
                             text="This Username is already taken.")
            if CustomUser.objects.filter(email=email).exists():
                user_data_has_error = True
                create_alert(
                    request=request, ID="email-used", type="error",
                    text="There is already an account tied to this email.")

            if not re.match(PASSWORD_PATTERN, password):
                user_data_has_error = True
                create_alert(
                    request=request, ID="password-invalid", type="error",
                    text="Password must be at least 8 characters long, include\
                         one uppercase letter, and one special character.")

            if user_data_has_error:
                return redirect("core:user_register")
            else:
                # create new user in database:
                new_user: CustomUser = CustomUser.objects.create_user(
                    first_name=first_name,
                    last_name=last_name,
                    email=email,
                    username=username,
                    password=password,
                )

                if form.data.get("invite_code", "") != "":
                    # It is required for the user to be logged in before
                    # attempting to use the invite
                    login(request, new_user)
                    join_family(request, token=form.data.get("invite_code"))

                    logout(request)

                CalendarEntry.objects.create(
                    title="First Step",
                    description="Created your FamilyThings account",
                    custom_user_id=new_user
                )

                create_alert(
                    request=request, ID="account-created", type="success",
                    text="Account has been successfully created. \
                        You may login now.")
                return redirect("core:user_login")


@update_user_session(require_family=False)
def user_final_step(request):
    """."""
    form: UserFinalizeForm = UserFinalizeForm(
        initial={'family_name': f"{request.user.full_name()}'s Family"})
    return render(request, "core/user_final_step.html", {'form': form})


@update_user_session()
def user_profile_page(request):
    """The User's overview section."""
    try:
        fam_user = FamilyUser.objects.get(
            custom_user_id=request.user,
            family_id=request.session["family_info"]["family_ID"])
        chat = FamilyChat.objects.filter(family_id=request.session["family_info"]["family_ID"])

        # Messenger
        # TODO: Move the Message creation to its own section
        if request.POST:
            try:
                Message.objects.create(
                    text=request.POST["text"],
                    custom_user_id=request.user,
                    family_chat_id=chat[0])
                request.POST = None
                redirect("core:user_profile")
            except (Exception):
                pass

        messages = []
        if len(chat) > 0:
            messages = Message.objects.filter(
                family_chat_id=chat[0],
                deleted=False).order_by(
                "created_on").reverse()[:10]

        #  Family Activities
        fam_users = FamilyUser.objects.filter(
            family_id=request.session["family_info"]["family_ID"]).exclude(
                custom_user_id=request.user)

        accomplishments = []
        for user in fam_users:
            try:
                user_accomp = FamilyUserAccomplishment.objects.filter(
                    family_user_id=user
                ).order_by("created").reverse()[0]

                # Get the creared/created date before proceeding with
                # the Accomplishment details.
                create_date = user_accomp.created

                user_accomp = user_accomp.accomplishment_id.serialized()
                user_accomp["cleared_by"] = user.custom_user_id.full_name()
                user_accomp["color"] = user.custom_user_id.color
                user_accomp["user_icon"] = user.custom_user_id.icon
                user_accomp["date"] = create_date
                user_accomp["fam_user_ID"] = str(user.id)
                user_accomp["email"] = user.custom_user_id.email
                accomplishments += [user_accomp]
            except (IndexError):
                pass

        return render(request, "core/user_profile.html", {
            'family': fam_user.serialized(),
            'family_activity': accomplishments,
            'chat': list(messages)
        })
    except (FamilyUser.DoesNotExist, IndexError) as e:
        print(e)
        return redirect("core:user_final_step")


@update_user_session()
def user_settings_page(request):
    """The User's settings page."""
    user: CustomUser = request.user

    #  We need to check for the birthday to prevent an AttributeError
    birthday = ""
    if user.birthday is not None:
        birthday = f"{user.birthday.year}-{user.birthday.day}-\
            {user.birthday.month}"

    form: UserSettingsForm = UserSettingsForm(
        #  Autofill form based on existing user settings
        initial={
            "first_name": request.user.first_name,
            "last_name": request.user.last_name,
            "language": user.lang_code,
            "color": user.color,
            "cursor": user.cursor,
            "birthday": birthday
        }
    )

    if request.POST or request.FILES:
        form = UserSettingsForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            user.first_name = form.cleaned_data.get("first_name")
            user.last_name = form.cleaned_data.get("last_name")
            user.birthday = form.cleaned_data.get("birthday")
            user.lang_code = form.cleaned_data.get("language")
            user.color = form.cleaned_data.get("color")
            user.cursor = form.cleaned_data.get("cursor", False)

            #  Upload and update the icon and background, if required
            if form.cleaned_data.get("user_icon") is not None:
                user.icon = form.cleaned_data.get("user_icon")

            if form.cleaned_data.get("background_image") is not None:
                user.background_image = form.cleaned_data.get(
                    "background_image")

            # Remove icon and background
            if form.cleaned_data.get("remove_icon"):
                user.icon = None

            if form.cleaned_data.get("remove_background"):
                user.background_image = None

            user.updated = timezone.now()
            update_session(
                request=request,
                lang_code=request.POST["language"],
                custom_cursor=user.cursor,
            )
            user.save()
            create_alert(request=request, ID="settings-updated", 
                         type="success",
                         text="Your settings have been saved.")

templates/core/bg_preview.html
{% load static %}
{% if image %}
    src='{% get_media_prefix %}{{image}}''
{% else %}
    src="{% static 'default_background.jpg' %}"
{% endif %}

templates/core/password_reset_sent.html
{% extends "site/site_base.html" %}
{% block title %}Reset Sent{% endblock title %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <div class="card shadow-lg border-0 rounded-3 text-center">
        <div class="card-header bg-success text-white">
          <h4 class="mb-0">Reset Link Sent</h4>
        </div>
        <div class="card-body">

          <p class="lead">
            A password reset link has been sent to your email.  
            Please note that it <b>expires in 10 minutes</b>!
          </p>

          <div class="mt-4">
            <a href="{% url 'core:user_login' %}" class="btn btn-success border-success">Go to Login</a>
            <a href="{% url 'core:user_register' %}" class="btn btn-outline-secondary">Sign Up</a>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>
{% endblock content %}

templates/core/temp_bg_preview.html
{% load static %}
{% if image %}
    src='{% get_media_prefix %}{{image}}''
{% else %}
    src="{% static 'default_background.jpg' %}"
{% endif %}

templates/core/user_final_step.html
{% extends "site/site_base.html" %}
{% block title %}Final Step -{% endblock %}
{% block content %}
<div id="final-step-wrapper" class="container">
    <div id="final-step" class="container rounded bg-dark p-2 pb-4 h-25 mh-25">
        {% include 'site/heading_large.html' with id="final-step" label='Final Step'%}
        <hr>
        <form id="family-form" method="post" class="m-auto w-75 d-flex">
            {% csrf_token %}
            <div id="new-family" class="w-50 mx-2 bg-body-tertiary rounded p-2 mt-3">
                <div class="w-100 m-auto pb-1 text-center fs-sm">
                    <span id="lb-new-family-hint">You can create your own Family here.</span><br>
                </div>
                <div class="d-block m-auto text-center" style="width: fit-content;">
                    {% include 'site/temp_form_field.html' with id="family-name" field=form.family_name %}
                    <button id="btn-create" class="btn btn-success border-success mt-4 m-auto text-center d-block" type="button">Create</button>
                </div>
            </div>
            <div id="family-invite" class="w-50 mx-2 bg-body-tertiary rounded p-2 mt-3">
                <div class="w-100 m-auto pb-1 text-center fs-sm">
                    <span id="lb-invite-hint">Already got a Family Invite? Add the code here.</span><br>
                </div>
                <div class="d-block m-auto text-center" style="width: fit-content;">
                    {% include 'site/temp_form_field.html' with id="" field=form.invite_code %}
                    <button id="btn-apply" class="btn btn-success border-success mt-4 m-auto text-center d-block" type="button">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $("#btn-create").click(function(event) {
        event.preventDefault(); // Prevents the button from creating the default HTTPRequest
        event.target.disabled = true; //  Disables the log in button

        enableLoadingScreen();  // Function is defined in site_js
        let form_data = $("#family-form")
        $.ajax({ 
            type: 'POST', url: '{% url "core:create_family" %}',
            data: form_data.serializeArray(),
            success: function(json) {
                createAlert(text=json["alert-message"], key="", type=json["alert-type"]);
                setTimeout(function() {window.location.replace("{% url 'core:user_profile' %}");}, 1000);
            },
            error: function(xhr, errmsg, err) {
                event.target.disabled = false;
                createAlert(xhr.responseText, key="", type="danger");
            }
        });
        disableLoadingScreen();
    });

    //"inviteField" is already defined in this imported section of code
    {% include 'core/js_check_invite.js' %}

    //Overwrite the invite button
    inviteButton = document.getElementById("btn-apply");
    inviteButton.disabled = true;

    $("#btn-apply").click(function(event) {
        event.preventDefault(); // Prevents the button from creating the default HTTPRequest
        event.target.disabled = true; // 

        enableLoadingScreen();  // 
        let form_data = $("#family-form")
        $.ajax({ 
            type: 'POST', url: '{% url "core:join_family" %}',data:{
                csrfmiddlewaretoken: '{{ csrf_token }}',
                token: currentToken
            },
            success: function(json) {
                createAlert(text=json["alert-message"], key="", type=json["alert-type"]);
                setTimeout(function() {window.location.replace("{% url 'core:user_profile' %}");}, 1000);
            },
            error: function(xhr, errmsg, err) {
                event.target.disabled = false;
                createAlert(xhr.responseText, key="", type="danger");
            }
        });
        disableLoadingScreen();
    });
</script>
{% endblock %}

templates/core/user_manage_family.html
{% extends "site/site_base.html" %}
{% block title %}Family Management - {% endblock %}
{% block content %}
{% load static %}
<script>
    function removeUser(btn) {
        if (confirm(`Are you sure you want to this?`)) {
            btn.disabled = true;
            
            $.ajax({ 
                type: 'POST', url: '{% url "core:remove_member" %}',
                data: {csrfmiddlewaretoken: '{{ csrf_token }}',
                    family_id: '{{family.ID}}', user_id: btn.value
                },
                success: function(json) {
                    createAlert(text=json["alert-message"], key="", type=json["alert-type"]);
                    location.reload();
                },
                error: function(xhr, errmsg, err) {
                    createAlert(xhr.responseText, key="", type="danger");
                    event.target.disabled = false;
                    btn.disabled = false;
                }
            });
        }
    }
    function toggleManagerRole(btn) {
        if (confirm(`Are you sure you want to this?`)) {
            btn.disabled = true;
            
            $.ajax({ 
                type: 'POST', url: '{% url "core:toggle_manager_role" %}',
                data: {csrfmiddlewaretoken: '{{ csrf_token }}',
                    family_id: '{{family.ID}}', user_id: btn.value
                },
                success: function(json) {
                    createAlert(text=json["alert-message"], key="", type=json["alert-type"]);
                    location.reload();
                },
                error: function(xhr, errmsg, err) {
                    createAlert(xhr.responseText, key="", type="danger");
                    event.target.disabled = false;
                    btn.disabled = false;
                }
            });
        }
    }
</script>
<div id="family-section" class="container-sm pb-4 w-100">
    {% include 'site/heading_section.html' with id="family-management" label="Family Management" %}
    <div id="family-manage" class="container rounded bg-dark p-2 h-25 mh-25">
        <div id="family-manage-wrapper" class="container d-flex flex-wrap rounded py-2">
            <div class="w-50 px-3">
                {% include 'site/heading_small.html' with id="members" title='Members' %}
                <table id="accomplishments-table" class="table table-striped bg-opacity-50" style="table-layout: fixed;">
                    <thead class="w-100 fs-sm">
                        <tr class="">
                            <th class="p-1" style="width: 5%;" scope="col">#</th>
                            <th class="p-1" id="lb-displayname" style="width: 28%;" scope="col">Display Name</th>
                            <th class="p-1" id="lb-username" style="width: 18%;" scope="col">Username</th>
                            <th class="p-1" id="lb-role" style="width: 14%;" scope="col">Role</th>
                            <th class="p-1" id="lb-member-joined" style="width: 17%;" scope="col">Joined</th>
                            <th class="p-1" id="" style="width: 13%;" scope="col"></th>
                        </tr>
                    </thead>
                    <tbody id="accomplishments-table-body" class="fs-sm">
                        {% for member in members %}
                            {% with info=member.serialized %}
                            <tr id="fam-user-{{info.ID}}" style="vertical-align: middle;">
                                <td class="p-1"><img id="dropdown-user-icon" class="border;" style="border: solid 2px !important; border-color: var(--bs-{{info.color}}) !important;" src="{% get_media_prefix %}{{info.icon}}" 
                                    onerror="this.onerror=null; this.src='{% static 'default-user.png' %}'" height="25" width="25" alt="{% get_media_prefix %}{{icon}}"></td>
                                <td class="p-1"><div class="rounded p-1 fs-sm me-2" style="background-color: var(--bs-{{info.color}}) !important; color: var(--bs-{{info.color}}-font) !important;">{{info.full_name}}</div></td>
                                <td class="p-1">{{info.username}}</td>
                                <td class="p-1">{% include 'header/temp_role_name.html' with manager=info.is_manager owner=family.owner name=info.username %}</td>
                                <td class="p-1">{{info.joined}}</td>
                                {% if request.user.username != info.username %}
                                    {% if family.owner == request.user.username or request.session.family_info.is_manager and info.username != family.owner and not info.is_manager %}
                                        <div class="dropdown">
                                            <td class="p-0"><button id="btn-actions" value="{{info.ID}}" type="button" data-bs-toggle="dropdown" class="dropdown-toggle btn btn-primary d-block m-auto mt-auto p-1 fs-sm" style="margin-top: 0.1em !important;">Actions</button>
                                            <ul class="dropend dropdown-menu fs-sm">
                                                {% if family.owner == request.user.username %}
                                                <li id="promote-user" value="{{info.ID}}" onclick="this.onclick=null; toggleManagerRole(this); this.disabled=true;" class="dropdown-item"> 
                                                    {% if info.is_manager %}
                                                        <span id="lb-set-as-member" class="text-success-emphasis">Set as Member</span>
                                                    {% else %}
                                                        <span id="lb-set-as-manager" class="text-info-emphasis">Set as Family Manager</span>
                                                    {% endif %}
                                                </li>
                                                <li><hr class="dropdown-divider"></li>
                                                {% endif %}
                                                <li id="remove-user" value='{{info.ID}}' onclick="this.onclick=null; removeUser(this); this.disabled=true;" class="dropdown-item text-danger"><span class="bi bi-x-circle"></span> <span id="lb-rm-from-family">Remove from Family</span></li>
                                            </ul>  
                                            </td>
                                        </div>
                                    {% else %}
                                        <td class="p-1"></td>
                                    {% endif %}
                                {% else %}
                                    <td class="p-1"></td>
                                {% endif %}
                            </tr>
                            {% endwith %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="w-50 px-3">
                {% include 'site/heading_small.html' with id="invites" title='Invites' %}
                <div class="bg-dark rounded-2 py-3 text-center">
                    <p id="lb-invite-code" class="p-1 m-0">Your Invite Code:</p>
                    <p id="invite-code" class="p-1 m-0">{{invite}}</p>
                </div>
                <button id="btn-generate-new" class="btn btn-primary border-primary mt-4 m-auto text-center d-block" type="button">Generate New</button>
            </div>
        </div>
    </div>
</div>
<script>
    $("#btn-generate-new").click(function(event) {
        if (confirm(`Are you sure you want to this?\n(This makes the current invite invalid!)`)) {
            event.preventDefault(); // Prevents the button from creating the default HTTPRequest
            event.target.disabled = true; //  Disables the log in button

            $.ajax({ 
                type: 'POST', url: '{% url "core:create_invite" %}',
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
                success: function(json) {
                    createAlert(text=json["alert-message"], key="", type=json["alert-type"]);
                    event.target.disabled = false;
                    $("#invite-code").text(json['new-token']);
                },
                error: function(xhr, errmsg, err) {
                    createAlert(xhr.responseText, key="", type="danger");
                    event.target.disabled = false;
                }
            });
        }
    });
</script>
{% endblock %}