accomplishment/urls.py
from django.urls import path, re_path
from . import views
from . import requests

# Ideally, its name is identical with the folder's
app_name = "accomplishment"

urlpatterns = [
     # path(<URL>, <view>, <name>)
     re_path(r"^(?:show=(?P<popup>[a-zA-Z_]+)/)?$", views.page_overview, name="overview"),

     # AJAX Urls
     re_path(r"^get/(?:amount=(?P<amount>[0-9]+)/)?(?:start=(?P<start>[0-9]+)/)?(?:selector='(?P<selector>[a-zA-Z]+)'/)?(?:key='(?P<key>[0-9a-zA-Z ]+)')?$",
          requests.get_entries, name="get"),
     path("get/recent/amount=<int:amount>",
          requests.get_recent, name="get_recent"),
     path("get/today/amount=<int:amount>",
          requests.get_obtained_today, name="obtained_today"),
     path("get/name=<str:name>",
          requests.get_by_name, name="get_by_name"),
     path("get/names",
          requests.get_names, name="get_names"),

     path("entry/get/id=<uuid:ID>",
          requests.get_accomp_by_id, name="get_by_id"),
     path("entry/edit/id=<uuid:ID>",
          requests.edit_accomp, name="edit_accomp"),
     path("entry/repeat",
          requests.repeat_accomplishment, name="repeat_accomp"),
     path("template/get", requests.get_template, name="get_template"),
     path("template/save", requests.save_template, name="save_template"),

     # Operations (Creating/Deleting)
     path("submit",
          requests.submit_accomplishment, name="submit_new"),
     path("delete/id=<uuid:ID>",
          requests.delete_accomplishment, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),  # Main App ('core')
    path("accomplishments/",  # Accomplishment
         include("accomplishment.urls", namespace='accomplishment')),
    path("admin/", admin.site.urls),
    path("finance/",          # Finance
         include("finance.urls", namespace='finance')),
    path("calendar/",          # Finance
         include("ft_calendar.urls", namespace='calendar')),
]

core/urls.py
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from core.session import switch_language, switch_family
from . import views, requests, user_auth

# Ideally, its name is identical with the folder's
app_name = "core"

core_urls = [
    # path(<URL>, <view>, <name>)
    path("", views.home, name="home"),
    path("login/", views.user_login_page, name="user_login"),
    path("register/", views.user_register, name="user_register"),
    path("register/final_step/", views.user_final_step, name="user_final_step"),
    path("profile/", views.user_profile_page, name="user_profile"),
    path("settings/", views.user_settings_page, name="user_settings"),
    path("family/", views.manage_family_page, name="manage_family"),

    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path("password_reset_sent/<str:reset_id>/", views.password_reset_sent, name="password_reset_sent"),
    path("reset_password/<str:reset_id>/", views.reset_password, name="reset_password"),

    # Authentication and Session (AJAX)
    path("auth/login", user_auth.process_login, name="request_login"),
    path("auth/logout", user_auth.process_logout, name="request_logout"),
    path("session/switch_language", switch_language,
         name="session_change_language"),
    path("session/switch_family?id=<int:id>", switch_family,
         name="session_switch_family"),

    # Family (AJAX)
    path("family/create", requests.create_family, name="create_family"),
    path("family/join", requests.join_family, name="join_family"),
    path("family/check_invite", requests.check_invite, name="check_invite"),
    path("family/create_invite", requests.create_invite, name="create_invite"),
    path("family/remove_member", requests.remove_from_family, name="remove_member"),
    path("family/toggle_manager_role", requests.toggle_manager_role, name="toggle_manager_role"),
    path("family/get_user", requests.get_user, name="get_user"),

    # Messenger (AJAX)
    path("message/delete/id=<uuid:id>", requests.delete_message,
         name="delete_message"),
    path("get_messages/", requests.get_messages, name="get_messages"),
]

urlpatterns = [
    # Import core_urls twice to include variants
    # with and without a provided language code
    re_path(r"^(?P<lang_code>[a-z]{2,3})/", include(core_urls)),
    path("", include(core_urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accomplishment/models/accomplishment.py
from django.db import models
from django.utils import timezone

from core.models.family_user import CustomUser
from .accomplishment_type import AccomplishmentType
from .measurement_type import MeasurementType
from core.utils import get_first_custom_user


class Accomplishment(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.CharField(
        max_length=1000,
        default="",
        blank=True)
    icon = models.CharField(max_length=20, blank=True, default="")
    created = models.DateTimeField(
        default=timezone.now
    )
    created_by = models.ForeignKey(
        CustomUser,
        on_delete=models.PROTECT,
        related_name="custom_user_created_accomplishments",
        default=get_first_custom_user
    )
    accomplishment_type_id = models.ForeignKey(
        AccomplishmentType,
        on_delete=models.PROTECT,
        related_name="accomplishments",
        default=None,
        blank=True,
        null=True
    )
    measurement_type_id = models.ForeignKey(
        MeasurementType,
        on_delete=models.PROTECT,
        related_name="measurements",
        default=None,
        blank=True,
        null=True
    )
    is_achievement = models.BooleanField(default=False)

    def serialized(self):
        measurement: str = None

        if (self.measurement_type_id):
            measurement = self.measurement_type_id.abbreviation

        output: dict = {
            'ID': self.id,
            'name': self.name, 'description': "".join(self.description.replace("'", "")),
            'icon': self.icon, 'is_achievement': self.is_achievement,
            'measurement': measurement,
        }

        if self.accomplishment_type_id:
            output['accomplishment_type'] = self.accomplishment_type_id.name
        return output

    class Meta:
        # White space as workaround for the ordering.
        verbose_name = "  Accomplishment"
        verbose_name_plural = "  Accomplishments"

accomplishment/models/accomplishment_type.py
import uuid
from django.db import models


class AccomplishmentType(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)

    class Meta:
        verbose_name = "Accomplishment Type"
        verbose_name_plural = "Accomplishment Types"

accomplishment/models/family_user_accomplishment.py
import uuid
from django.db import models

from core.models.family_user import FamilyUser
from core.models.custom_user import CustomUser
from .accomplishment import Accomplishment


class FamilyUserAccomplishment(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    family_user_id = models.ForeignKey(
        FamilyUser,
        on_delete=models.CASCADE,
        related_name="accomplishments",
        editable=False
    )
    accomplishment_id = models.ForeignKey(
        Accomplishment,
        on_delete=models.CASCADE,
        related_name="family_user_accomplishments",
        null=True,
        blank=True,
        editable=False
    )
    measurement_quantity = models.DecimalField(
        null=True,
        blank=True,
        decimal_places=2,
        max_digits=18
    )
    created = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )
    from_date = models.DateTimeField(
        null=True,
        blank=True
    )
    to_date = models.DateTimeField(
        null=True,
        blank=True
    )
    created_by = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="created_family_user_accomplishments",
        editable=False
    )
    chore_assignment_id = models.ForeignKey(
        CustomUser,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="chore_completions",
        editable=False
    )

    def serialized(self) -> dict:
        output = self.accomplishment_id.serialized()
        output['created_date'] = self.created.strftime("%Y-%m-%d")
        output['cleared_date'] = self.to_date.strftime("%Y-%m-%d")
        output['measurement_quantity'] = self.measurement_quantity

        return output

    def get_accomplishment(self):
        return self.accomplishment_id

    class Meta:
        verbose_name = " Family User Accomplishment"
        verbose_name_plural = " Family User Accomplishments"

accomplishment/models/measurement_type.py
import uuid
from django.db import models


class MeasurementType(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000, null=True, blank=True)
    abbreviation = models.CharField(max_length=20)

    class Meta:
        verbose_name = "Measurement Type"
        verbose_name_plural = "Measurement Types"

accomplishment/forms/accomplishment.py
from django import forms
from django.utils import timezone


class AccomplishmentForm(forms.Form):
    name = forms.CharField(
        label="Name", max_length=100, required=True)
    accomplishment_type = forms.CharField(
        label="Category", max_length=100, required=False)
    description = forms.CharField(label="Description", max_length=1000,
        widget=forms.Textarea, required=False)
    icon = forms.CharField(
        label="", max_length=40, required=True, widget=forms.HiddenInput())
    measurement = forms.CharField(max_length=4,
        label="Unit", required=False)
    measurement_quantity = forms.DecimalField(
        label="Value", required=False, min_value=0, widget=forms.NumberInput())
    timeframe = forms.BooleanField(
        label="Timeframe", required=False)
    date_from = forms.DateField(label="From", required=False, initial=timezone.now, widget=forms.DateInput())
    date_to = forms.DateField(label="To", required=False, initial=timezone.now, widget=forms.DateInput())
    date = forms.DateField(label="Cleared", required=False, initial=timezone.now, widget=forms.DateInput())
    is_achievement = forms.BooleanField(label="Spec. Achievement", required=False)
    #  Used in case the user wants to repeat an existing one
    is_repeat = forms.BooleanField(label="", required=False)

    # Link the widgets to the auto generated datalists (see constants.py for the elements)
    accomplishment_type.widget.attrs.update({"list": "type-suggestions", 'placeholder': 'Optional', "style": "width: 12em;"})
    measurement.widget.attrs.update({"list": "measurement-suggestions"})

    name.widget.attrs.update({"style": "width: 12em;"})

    # By default, Django creates a Textarea with 10 rows, which is too much.
    description.widget.attrs.update({"rows": "3", 'style': "width: 24em;", 'placeholder': 'Optional'})

    # Add Bootstrap classes to the fields
    is_achievement.widget.attrs.update({"class": "form-check-input", "style": "width: 32px; height: 32px; margin: 0;"})

    # Size tweaks for the measurement section
    measurement_quantity.widget.attrs.update({"style": "width: 5em; font-size: 1.15em;", 'placeholder': '0'})
    measurement.widget.attrs.update({"style": "width: 2.5em; font-size: 1.15em;", 'placeholder': 'x'})

    accomplishment_type.widget.attrs.update({"style": "width: 12em; height: 2em;"})

    # The icon selection is handled through the page's JavaScript
    icon.widget.attrs.update({"style": "display: none;"})
    is_repeat.widget.attrs.update({"style": "display: none;"})

    timeframe.widget.attrs.update({"class": "form-check-input"})

accomplishment/views.py
import zoneinfo
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from .models import Accomplishment, FamilyUserAccomplishment, AccomplishmentType, MeasurementType
from .forms.accomplishment import AccomplishmentForm
from . import constants
from core.session import update_user_session, create_alert, get_locale_text
from core.models.custom_user import CustomUser


@update_user_session()
def page_overview(request, popup: str = ""):
    """An overview of an User's Accomplishments."""

    recent_additions = Accomplishment.objects.filter(
                    created_by=request.user.id).order_by('-created').values()[:15]

    return render(
        request, "accomp_overview.html",
        {
            'recent_additions': list(reversed(Accomplishment.objects.filter(id__in=recent_additions))),
            'colors': ['red', 'blue', 'green', 'orange', 'purple', 'cyan'],
            'icons': constants.ICONS,
            'categories': constants.CATEGORIES,
            'measurements': constants.MEASUREMENTS,
            'form': AccomplishmentForm(),
            'popup': popup
        })


@update_user_session()
def page_new_accomplishment(request, ID: int = -1, name: str = ""):
    """."""
    form: AccomplishmentForm = AccomplishmentForm()

    if name != "":
        form = AccomplishmentForm(initial={'name': name})

    if ID != -1:
        accom: Accomplishment = Accomplishment.objects.get(id=ID)
        form = AccomplishmentForm(initial={
            'name': accom.name,
            'description': accom.description,
            'icon': accom.icon,
            'is_achievement': accom.is_achievement,
            'measurement': accom.measurement_type_id.abbreviation
        })

    return render(
        request, "accomp_add_new.html",
        {
            "form": form,
            "icons": constants.ICONS,
            "initial": form.initial
        })


def datetime_from_field(form: AccomplishmentForm, field: str = "",
                        tz: str = "Europe/Paris"):
    return timezone.datetime(
        year=int(form.data[field+"_year"]),
        month=int(form.data[field+"_month"]),
        day=int(form.data[field+"_day"]),
        tzinfo=zoneinfo.ZoneInfo(tz))


@update_user_session()
def page_edit_user_accomplishment(request, ID: int = -1, cache_last_visited_page=False):
    """."""
    form: AccomplishmentForm = AccomplishmentForm()

    if ID != -1:
        accom: FamilyUserAccomplishment = FamilyUserAccomplishment.objects.get(id=ID)

        if (request.POST):
            form = AccomplishmentForm(data=request.POST)

            if (request.POST["measurement_quantity"] == ""):
                accom.measurement_quantity = 0
            else:
                accom.measurement_quantity = int(request.POST.get("measurement_quantity", 0))

            accom.from_date = datetime_from_field(form=form, field="date_from")
            accom.to_date = datetime_from_field(form=form, field="date_to")
            accom.save()

            return redirect("accomplishment:overview")

        form = AccomplishmentForm(data={
            'measurement': accom.accomplishment_id.measurement_type_id,
            'measurement_quantity': accom.measurement_quantity,
            'date_from': accom.from_date.astimezone(zoneinfo.ZoneInfo("Europe/Paris")),
            'date_to': accom.to_date.astimezone(zoneinfo.ZoneInfo("Europe/Paris")),
        })

        return render(
            request, "accomp_edit_milestone.html", {"form": form})


@update_user_session()
def page_edit_accomplishment_details(request, ID=-1):
    """."""
    form: AccomplishmentForm = AccomplishmentForm()
    if ID != -1:
        accom_details: Accomplishment = FamilyUserAccomplishment.objects.get(
            id=ID).accomplishment_id

        if (request.POST):
            form = AccomplishmentForm(data=request.POST)
            accom_details.name = request.POST["name"]
            accom_details.description = request.POST["description"]
            accom_details.icon = request.POST["icon"]
            if request.POST.get("accomplishment_type", "") != "":
                accom_details.accomplishment_type_id = AccomplishmentType.objects.get_or_create(
                        name=request.POST["accomplishment_type"])[0]
            if request.POST.get("measurement", "") != "":
                accom_details.measurement_type_id = MeasurementType.objects.get_or_create(
                        abbreviation=request.POST["measurement"])[0]
            accom_details.save()
            return redirect("accomplishment:overview")

        accomp_data = accom_details.serialized()

        form = AccomplishmentForm(data=accomp_data)

        return render(
            request, "accomp_edit_details.html", {
                "form": form, "icons": constants.ICONS,
                "initial": accomp_data})

accomplishment/templates/accomp_overview.html
{% extends "site/site_base.html" %}
{% block title %}Accomplishments - {% endblock %}
{% block popups %}
    {% include 'popup_name_prompt.html' %}
    {% include 'popup_create_accomp.html' with icons=icons %}
    {% include 'popup_edit_accomp.html' %}
    {% include 'popup_repeat_accomp.html' %}
    {% include 'popup_edit_template.html' %}
{% endblock %}
{% block content %}
<div id="accomplishments-overview" class="container-sm pb-4 w-100">
    {% include 'site/heading_section.html' with label="Accomplishments" id="accomplishments" %}
    <div id="accomplishments" class="container rounded bg-dark p-2 h-25 mh-25">
        <div id="accomplishments-wrapper" class="container rounded py-2">
            <div class="d-flex justify-content-between flex-wrap p-3">
                <div style="width: 65%">
                    {% include 'site/heading_small.html' with label="All Activity" id="all-activity" %}
                    <div class="d-flex flex-wrap justify-content-between pb-2">
                        <form id="filter-form" class="w-100">
                            <div class="d-flex w-50 ms-auto">
                                <select id="filter-selector" class="form-select fs-sm position-relative">
                                    <option selected value="name">Name</option>
                                    <option value="uncategorized">Name (w/o Category)</option>
                                    <option value="achievement">Name (Sp. Achievement)</option>
                                    <option value="category">Category</option>
                                </select>
                                <input id="search-filter" class="form-control me-3 fs-sm" style="width: 15em;" type="search" placeholder="Filter Accomplishments..." aria-label="Search">
                            </div>
                            <button id="" type="submit" class="d-none"></button>
                        </form>
                    </div>
                    <div class="position-relative pe-3" style="height: 34em;">
                        <table id="accomplishments-table" class="table table-striped bg-opacity-50" style="table-layout: fixed;">
                            <thead class="w-100 fs-sm">
                                <tr class="">
                                    <th class="p-1" style="width: 3%;" scope="col">#</th>
                                    <th class="p-1" id="id_name" style="width: 27%;" scope="col">Name</th>
                                    <th class="p-1" id="lb-measurement" style="width: 18%;" scope="col">Measurement</th>
                                    <th class="p-1" id="lb-category" style="width: 20%;" scope="col">Category</th>
                                    <th class="p-1" id="lb-created-on" style="width: 20%;" scope="col">Created on</th>
                                    <th class="p-1" id="lb-cleared-on" style="width: 20%; display: none;" scope="col">Cleared on</th>
                                    <th class="p-1" style="width: 12%;" scope="col"></th>
                                </tr>
                            </thead>
                            <tbody id="accomplishments-table-body" class="fs-sm">
                                
                            </tbody>
                        </table>
                        <div id="table-buttons" class="w-100 pe-3 d-flex justify-content-between position-absolute bottom-0 start-50 translate-middle-x">
                            <button id="previous-button" type="button" class="bi bi-caret-left-fill h4 d-block"></button>
                            <div class="font-monospace"><span id="lb-entries">Showing Entries</span> <span id="range-start"></span>-<span id="range-end"></span> (<span id="lb-entries2">found</span> <span id="range-total"></span> <span id="lb-entries3">total</span>)</div>
                            <button id="next-button" type="button" class="bi bi-caret-right-fill h4 d-block"></button>
                        </div>
                    </div>
                </div>
                <div style="width: 35%">
                    {% include 'site/heading_small.html' with title="Had any recent Accomplishments?" id="any-recent-accomps" class='text-center pt-1' %}
                    <div id="new-accomplishment-wrapper" class="w-auto m-auto pb-4">
                        <a id="add-new-button" class="nav-link m-auto tooltip-source" style="width: fit-content;" data-tooltip-context="Add New">
                            <h4 id="new-accomplishment-label" class="text-center m-0 p-1 bg-dark rounded p-1">
                            <i id="new-accomplishment-icon" class="bi bi-plus-square-fill text-center fs-1"></i></h4>
                        </a>
                    </div>
                    {% include 'site/heading_small.html' with title="Recent Additions (Click to repeat)" id="recent-additions" class='text-center pt-1' %}
                    <div class="d-flex justify-content-center flex-wrap gap-1" style="width: fit-content;">
                        {% for entry in recent_additions %}
                            <a data-accomp-data="{{entry.serialized}}" onclick="openRepeat(this)" value={{entry.id}} class="link-underline link-underline-opacity-0 tooltip-source" data-tooltip-context="Repeat" data-tooltip-content='"{{entry.name}}"'>
                                {% with color=colors|random %}
                                <div class="rounded-2 p-1" style="color: var(--bs-{{color}}-font); background-color: var(--bs-{{color}});">{{entry.name}} <span class="bi bi-repeat"></span></div>
                                {% endwith %}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    #next-button:disabled,
    #previous-button:disabled {
        filter: grayscale(.5);
        color: var(--bs-gray-700);
        border-color: var(--bs-gray-700) !important;
    }
</style>
<script>
    var getAccompURL = "{{HOST}}/accomplishments/entry/get/id=";
    var editAccompURL = "{{HOST}}/accomplishments/entry/edit/id=";
    var repeatAccompURL = "{{HOST}}/accomplishments/entry/repeat";
    var getTemplateURL = "{% url 'accomplishment:get_template' %}"
    var saveTemplateURL = "{% url 'accomplishment:save_template' %}"
    var nameCheckURL = "{{HOST}}/accomplishments/get/name=";
    var getNamesURL = "{% url 'accomplishment:get_names' %}"
    var currentAJAXURL = editAccompURL;


    {% include 'js_accomp_search_table.js' %}
    {% include 'js_accomp_edit_accomp_prompt.js' %}
    {% include 'js_accomp_repeat_accomp_prompt.js' %}
    {% include 'js_accomp_name_prompt.js' %}
    {% include 'js_accomp_create_accomp_prompt.js' %}
    {% include 'js_accomp_edit_template_prompt.js' %}


    setTimeout(
        function(){
            if ("{{popup}}" == "add_new") {
                resetNamePrompt();
                openPopup("name-prompt-popup");
            }
        }
    , 80)
</script>
{% endblock %}

accomplishment/templates/popup_edit_accomp.html
<div id="edit-accomp-popup" class="container popup" style="display: none; margin-bottom: 11rem !important; min-width: 650px;">
{% include 'site/heading_section.html' with label="Edit Accomplishment" id="edit-user-accomp" class='m-auto' %}
<div class="rounded bg-dark px-5 d-block pb-4 position-relative">
    <div id="bg-icons" class="position-relative no-ptr-evt">
        <span class="bi bi-journal-text background-bi bi-edit-accomp h1 p-0 m-0 position-absolute"></span>
        <span class="bi bi-pen background-bi bi-edit-accomp h1 p-0 m-0 position-absolute"></span>
    </div>
    <div id="edit-accomp-wrapper" class="px-5 py-2">
        {% include 'temp_accomp_info.html' with show_date=True %}
        <form id="edit-accomp-form" method="post" class="m-auto d-flex justify-content-center flex-wrap gap-5">
            {% csrf_token %}
            <div id="measurement-settings">
                <div id="measurement-section" class="d-flex gap-2 ps-4 pt-3">
                    {% include 'site/temp_form_field.html' with id="measurement-value" field=form.measurement_quantity %}
                    {% include 'site/temp_form_field.html' with id="measurement-type" field=form.measurement %}
                </div>
            </div>
            {% include 'temp_timeframe_selection.html' with popup='edit-accomp-popup' %}
            </div>
            <div class="d-flex gap-2 pt-4 m-auto" style="width: fit-content;">
                <button id="btn-apply-changes" class="btn btn-success border-success" type="button">Submit Change</button>
                <button id="btn-abort" class="btn-abort-edit btn btn-danger" type="button">Abort</button>
            </div>
        </form>
    </div>
</div>

accomplishment/templates/temp_accomp_icon_selection.html
<div class="w-100">
    {% include 'site/temp_form_field.html' with id="accomp-icon" field=form.icon hidden=True %}{# Hidden Field #}
    <div class="m-auto" style="width: fit-content; gap:.125em">
        <div id="lb-accomp-icon">
            Icon
        </div>
        <div class="d-flex flex-wrap">
        {% for icon in icons %}
            {% if icon == "$BREAK$" %}
                </div><div class="d-flex flex-wrap m-auto w-fit">
            {% elif icon == "$SPACE$" %}
                <div style="width: .5em;"></div>
            {% else %}
                <button id="icon-btn-{{icon}}" type="button" onclick="input_change_value(this, '#{{popup}} #id_icon')", value="{{icon}}" class="icon-btn btn btn-dark border border-secondary p-1 m-0 rounded tooltip-source"
                data-tooltip-context="{{icon}}">
                    <div class="bi bi-{{icon}} h4 p-0 m-0"></div>
                </button></i>
            {% endif %}
        {% endfor %}
        </div>
    </div>
<div>
<script>
    var source = "{{popup}}"
    var iconField = document.querySelector(`#${source} #id_icon`);

    iconField.disabled = false;

    function unfocus_all(elements){
        elements.forEach(function(element, i) {
            element.classList.remove("active");
        })
    }

    async function input_change_value(button, input){
        if (document.querySelector(input).disabled){
            return; /* Only accept changes if the input field is active */
        }

        document.querySelector(input).value = button.value;
        unfocus_all(document.querySelectorAll(".icon-btn"));

        button.classList.add("active");
    }

    /* Check if an icon (when repeating an Accomplishment) is defined, if not use the default icon. */
    if ('{{initial.icon}}' != ''){ input_change_value(document.querySelector(`#${source} #icon-btn-{{initial.icon}}`), `#${source} #id_icon`); }
        else{ input_change_value(document.querySelector(`#${source} .icon-btn`), `#${source} #id_icon`); }
</script>

accomplishment/templates/temp_accomp_info.html
<div class="w-fit m-auto px-3 py-2 mb-3 text-center">
    <span id="edit-accomp-icon"> </span><span id="edit-accomp-name" class="h5"></span><br>
    {% if show_date %}<span id="lb-created-on">Created on</span> <span id="edit-accomp-created"></span>{% endif %}
</div>

accomplishment/templates/temp_timeframe_selection.html
<div id="timeframe-section" class="d-flex flex-column w-fit m-auto p-0" style="line-height: 1.9em; max-height: 100px; height: 100px; width: 190px;">
    <div id="field-cleared" class="mx-auto" style="height: 120px;">
        <div id="lb-cleared-on" class="mx-auto w-fit">Cleared on</div>
        <input type="date" class="form-control" id="id_date" style="padding: .2em; text-transform: uppercase; width: 120px;" placeholder="Today">
    </div>
    <div id="field-from" class="d-none" style="height: 60px;">
        <div id="lb-date-from" style="width: 3em;">From</div>
        <input type="date" class="form-control fs-sm" id="id_date_from" style="padding: .2em; text-transform: uppercase; width: 120px; height: 2.5em;" placeholder="Today">
    </div>
    <div id="field-to" class="d-none" style="height: 60px;">
        <div id="lb-date-to" style="width: 3em;">To</div>
        <input type="date" class="form-control fs-sm" id="id_date_to" style="padding: .2em; text-transform: uppercase; width: 120px; height: 2.5em;" placeholder="Today">
    </div>
    {% include 'site/temp_form_field.html' with id="timeframe" field=form.timeframe field_class='form-switch d-flex p-0 mb-0 m-0 fs-sm mx-auto' %}
</div>
<script>
    document.querySelector(`#{{popup}} #id_timeframe`).addEventListener("click", function(event){
        if (event.target.checked){
            document.querySelector(`#{{popup}} #id_date`).deactivated = true;
            document.querySelector(`#{{popup}} #field-cleared`).className = "d-none";
            document.querySelector(`#{{popup}} #id_date_from`).deactivated = false;
            document.querySelector(`#{{popup}} #field-from`).className = "d-flex gap-2 fs-sm m-auto";
            document.querySelector(`#{{popup}} #id_date_to`).deactivated = false;
            document.querySelector(`#{{popup}} #field-to`).className = "d-flex gap-2 fs-sm m-auto";
        }
        else {
            document.querySelector(`#{{popup}} #id_date`).deactivated = false;
            document.querySelector(`#{{popup}} #field-cleared`).className = "mx-auto";
            document.querySelector(`#{{popup}} #id_date_from`).deactivated = true;
            document.querySelector(`#{{popup}} #field-from`).className = "d-none";
            document.querySelector(`#{{popup}} #id_date_to`).deactivated = true;
            document.querySelector(`#{{popup}} #field-to`).className = "d-none";
        }
    })
</script>